courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	
	url(r'^$', views.course_list),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/', views.step_detail),
	url(r'(?P<pk>\d+)', views.course_detail),

]

home_page/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$', views.home_page),
    ]

learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello_world/$', views.hello_world),
    url(r'^', include('home_page.urls')),
    url(r'^courses/', include('courses.urls')),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/', include('courses.urls')),
    url(r'(?P<pk>\d+)', include('courses.urls')),

]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models

# Create your models here.

class Course(models.Model):

	created_at = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=200)
	description = models.TextField()

	def __str__(self):

		return self.title


class Step(models.Model):

	title = models.CharField(max_length=200)
	description = models.TextField()
	content = models.TextField(blank=True, default='')
	order = models.IntegerField(default=0)
	course = models.ForeignKey(Course)

	class Meta:

		ordering = ['order',]

	def __str__(self):

		return self.title

home_page/models.py
from django.db import models

# Create your models here.

courses/views.py
from django.shortcuts import get_object_or_404, render
from .models import Course, Step

# Create your views here.

def course_list(request):

	courses = Course.objects.all()

	return render(request, 'courses/course_list.html',{'courses':courses})

def course_detail(request, pk):

	course = get_object_or_404(Course, pk=pk)

	return render(request, 'courses/course_detail.html', {'course':course})

def step_detail(request, course_pk, step_pk):

	step = get_object_or_404(Step,course_id=course_pk, pk=step_pk)

	return render(request, 'courses/step_detail.html', {'step':step})

home_page/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):

    return render(request, 'home_page/home_page.html')

learning_site/views.py
from django.shortcuts import render

def hello_world(request):

	return render(request, 'hello.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}

    <article>

        <h2>{{ course.title }}</h2>
        {{ course.description }}

        <section>

            {% for step in course.step_set.all %}

            <h3>{{ step.title }}</h3>
            {{ step.description }}

            {% endfor %}
        </section>
    </article>

{% endblock%}

courses/templates/courses/course_list.html
{% for course in courses%}

<h2>{{course.title}}</h2>
{{course.description}}

{% endfor %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %}{{step.title}}-{{step.course.title}}{% endblock %}

{% block content %}

<article>

    <h2>{{ step.course.title }}</h2>

    <h3>{{ step.title}} </h3>

    {{ step.content|linebreaks }}

</article>

{% endblock %}

home_page/templates/home_page/home_page.html
{% load staticfiles %}


<!DOCTYPE <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <title>Home Page</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Brand</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li>
                <li><a href="courses/">Courses</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>
              <form class="navbar-form navbar-left">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
              </form>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>

    <div class="jumbotron text-center" >

        <div class="container leadtext">

            <h1>Welcome to My Learning Site.</h1>

            <hr>

            <div class="row panel">
              <div class="col-md-4">

                  <div class="panel panel-success">
                      <div class="panel-heading">
                        <h3 class="panel-title">Panel title</h3>
                      </div>
                      <div class="panel-body">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.
                          <br>
                          <br>
                          <a class="btn btn-success btn-sm" href="#" role="button">Link</a>
                      </div>
                  </div>

              </div>
              <div class="col-md-4">

                  <div class="panel panel-danger">
                      <div class="panel-heading">
                        <h3 class="panel-title">Panel title</h3>
                      </div>
                      <div class="panel-body">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.

                        <br>
                        <br>
                        <a class="btn btn-danger btn-sm" href="#" role="button">Link</a>

                      </div>
                  </div>

              </div>

                <div class="col-md-4">

                  <div class="panel panel-primary">
                      <div class="panel-heading">
                        <h3 class="panel-title">Panel title</h3>
                      </div>
                      <div class="panel-body">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt.

                          <br>
                          <br>
                          <a class="btn btn-primary btn-sm" href="#" role="button">Link</a>


                      </div>
                  </div>

                </div>

            </div>



            <hr>


            <a href="courses/" class="btn btn-success pull-center text-primary btn-lg"  role="button">View Our Courses</a>

        </div>
    </div>


</body>
</html>

templates/hello.html
{% extends "layout.html" %}

{% load staticfiles %}

<!DOCTYPE <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'layout.css' %}">

    <title>{% block title %}Hello World{% endblock %}</title>
</head>
<body>

    <div class="container">

        {% block content %}


            <h1>Welcome</h1>

            <p>Hello World</p>

            <div class="row">
              <div class="col-md-4">

                  <div class="panel panel-danger">
                      <div class="panel-heading">
                        <h3 class="panel-title">Panel title</h3>
                      </div>
                      <div class="panel-body">
                        Panel content
                      </div>
                  </div>

              </div>
              <div class="col-md-4">

                  <div class="panel panel-danger">
                      <div class="panel-heading">
                        <h3 class="panel-title">Panel title</h3>
                      </div>
                      <div class="panel-body">
                        Panel content
                      </div>
                  </div>

              </div>

                <div class="col-md-4">

                  <div class="panel panel-danger">
                      <div class="panel-heading">
                        <h3 class="panel-title">Panel title</h3>
                      </div>
                      <div class="panel-body">
                        Panel content
                      </div>
                  </div>

                </div>

            </div>




        {% endblock %}

    </div>

</body>




</html>

templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>

<html lang="en">

    <head>

        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

    </head>


    <body>

        <div class="site-container">

            {% block content %}{% endblock %}

        </div>



    </body>
</html>